# アプリケーションのポート
Port = "3000"
PublicKeyPath = "./public-key.pem"
[database]
    # MySQL接続設定
    User = "root"
    Password = ""
    Database = "go_vue"
    Host  = "localhost"
    Port = "3306"
    Debug = true